version: 2
jobs:
  build:
    working_directory: ~/billboard-generator
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: billboard-generator-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: billboard-generator-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - 'node_modules'
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      # - run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
